data:
  max_size: 320
  mean:
  - 0.45
  - 0.45
  - 0.45
  min_size: 256
  num_frames_to_sample: 8
  permute_color_frame: 1
  resize_to: 224
  std:
  - 0.225
  - 0.225
  - 0.225
dataset:
  batch_size: 8
  dataset_path: dataset/ucf_action_grouped_augmented_ttv_mp4
  path_dataset_anomaly_csv: dataset/ucf_action_grouped_augmented_ttv_mp4/df_anomaly.csv
  path_dataset_test_csv: dataset/ucf_action_grouped_augmented_ttv_mp4/df_test.csv
  path_dataset_train_csv: dataset/ucf_action_grouped_augmented_ttv_mp4/df_train.csv
  path_dataset_val_csv: dataset/ucf_action_grouped_augmented_ttv_mp4/df_val.csv
model:
  dim_autoencoder_layers: 512,256,128
  do_test: 1
  do_train: 0
  dropout: 0.3
  freeze_layers: 1
  init_dim: 768
  layer_start_unfreeze: 0
  learning_rate: 0.001
  lr_factor: 0.1
  name_time_model: timesformer
  num_autoencoder_layers: 3
  num_epoch: 30
  number_of_classes: 7
  saving_dir_experiments: results_train_autoencoder/timesformer/
  saving_dir_model: v1
  scheduler_step_size: 10
  scheduler_type: StepLR
